export const links = [
  {
    href: "https://www.w3.org/html/",
    src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg",
    alt: "html5",
    width: "72",
    height: "72",
  },
  {
    href: "https://www.w3schools.com/css/",
    src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg",
    alt: "css3",
    width: "72",
    height: "72",
  },
  {
    href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg",
    alt: "javascript",
    width: "72",
    height: "72",
  },
  {
    href: "https://www.typescriptlang.org/",
    src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/typescript/typescript-original.svg",
    alt: "typescript",
    width: "72",
    height: "72",
  },
  {
    href: "https://reactjs.org/",
    src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original-wordmark.svg",
    alt: "react",
    width: "72",
    height: "72",
  },
  {
    href: "https://nextjs.org/",
    src: "https://cdn.worldvectorlogo.com/logos/nextjs-2.svg",
    alt: "nextjs",
    width: "72",
    height: "72",
  },
  {
    href: "https://nodejs.org",
    src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original-wordmark.svg",
    alt: "nodejs",
    width: "72",
    height: "72",
  },
  {
    href: "https://expressjs.com",
    src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/express/express-original-wordmark.svg",
    alt: "express",
    width: "72",
    height: "72",
  },
  {
    href: "https://www.elastic.co",
    src: "https://www.vectorlogo.zone/logos/elastic/elastic-icon.svg",
    alt: "elasticsearch",
    width: "72",
    height: "72",
  },
  {
    href: "https://keystonejs.com/",
    src: "./keystonejs.svg",
    alt: "keystone",
    width: "72",
    height: "72",
  },
  {
    href: "https://graphql.org",
    src: "https://www.vectorlogo.zone/logos/graphql/graphql-icon.svg",
    alt: "graphql",
    width: "72",
    height: "72",
  },
  {
    href: "https://www.mongodb.com/",
    src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/mongodb/mongodb-original-wordmark.svg",
    alt: "mongodb",
    width: "72",
    height: "72",
  },
  {
    href: "https://www.mysql.com/",
    src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original-wordmark.svg",
    alt: "mysql",
    width: "72",
    height: "72",
  },
  {
    href: "https://www.postgresql.org",
    src: "https://raw.githubusercontent.com/devicons/devicon/master/icons/postgresql/postgresql-original-wordmark.svg",
    alt: "postgresql",
    width: "72",
    height: "72",
  },
];
